version: '3.9'

services:
  email-sender-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-sender-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
